pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                git 'https://github.com/Dimitria-Dev/micro-services.git'
                sh './mvnw clean install'
            }
        }
        stage('Test') {
            steps {
                sh './mvnw test'
            }
            post {
                always {
                    junit '**/target/surefire-reports/TEST-*xml'
                }
            }
        }
    }
}