pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                git 'https://github.com/Dimitria-Dev/micro-services.git'
                sh './mvnw clean install'
            }
        }
    }
}