pipeline {
    agent any

    stages {
        stage('Checkout'){
            checkout scm
        }

        stage('Build') {
            steps {
                git 'https://github.com/Dimitria-Dev/micro-services.git'
                sh 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }

        }
    }
}